version: '3'
services:
  router:
    image: "iitsoftware/swiftmq-ce:12.0.2"
    ports:
      - "4001:4001"
    networks:
      fdnet:
        ipv4_address: 172.99.0.2
    volumes:
        - ${pwd}/router/data:/swiftmq/data
    extra_hosts:
        - "dockerhost:${myIP}"
  flowdirector:
    image: "flowdirector/fdserver:1.0.1"
    ports:
        - "8080:8080"
    networks:
      fdnet:
        ipv4_address: 172.99.0.3
    volumes:
        - ${pwd}/fdserver/data/apps:/flowdirector/apps
        - ${pwd}/fdserver/data/log:/flowdirector/log
        - ${pwd}/fdserver/data/config:/flowdirector/config
    extra_hosts:
        - "dockerhost:172.99.0.2"

networks:
  fdnet:
    ipam:
      driver: default
      config:
        - subnet: "172.99.0.0/16"
