#!/bin/bash

export myIP=`ifconfig $(netstat -rn | grep -E "^default|^0.0.0.0" | head -1 | awk '{print $NF}') | grep 'inet ' | awk '{print $2}' | grep -Eo '([0-9]*\.){3}[0-9]*'`
export pwd=`pwd`

case "$1" in
  start)
    docker-compose -f docker-compose.yml pull flowdirector
		docker-compose -f docker-compose.yml up -d
    ;;
  stop)
		docker-compose -f docker-compose.yml down -t 30
    ;;
  status)
    docker ps
    ;;
  *)
    echo "Usage: $N {start|stop|status}"
	  exit 1
    ;;
esac
exit 0
